import { StatusColorPipe } from './status-color.pipe';

describe('StatusColorPipe', () => {
    it('create an instance', () => {
        const pipe = new StatusColorPipe();
        expect(pipe).toBeTruthy();
    });

    it('test status color intention', () => {
        const pipe = new StatusColorPipe();
        const res = pipe.transform('BOOKED');
        expect(res).toBe('success');
        let result = pipe.transform('Published');
        expect(res).toBe('success');
        result = pipe.transform('PUBLISHED');
        expect(result).toBe('success');
        result = pipe.transform(true);
        expect(result).toBe('success');
        result = pipe.transform('CANCELLED');
        expect(result).toBe('danger');
        result = pipe.transform('ENTERED_IN_ERROR');
        expect(result).toBe('danger');
        result = pipe.transform('SUBMITTED');
        expect(result).toBe('success');
        result = pipe.transform('PROCESSED');
        expect(result).toBe('success');
        result = pipe.transform('processed');
        expect(result).toBe('success');
        result = pipe.transform('FINISHED');
        expect(result).toBe('success');
        result = pipe.transform('DELIVERED');
        expect(result).toBe('success');
        result = pipe.transform('RECEIVED');
        expect(result).toBe('success');
        result = pipe.transform('ACTIVE');
        expect(result).toBe('success');
        result = pipe.transform('active');
        expect(result).toBe('success');
        result = pipe.transform('Active');
        expect(result).toBe('success');
        result = pipe.transform('COMPLETED');
        expect(result).toBe('success');
        result = pipe.transform('completed');
        expect(result).toBe('success');
        result = pipe.transform('Completed');
        expect(result).toBe('success');
        result = pipe.transform('COMPLETE');
        expect(result).toBe('success');
        result = pipe.transform('complete');
        expect(result).toBe('success');
        result = pipe.transform('ARRIVED');
        expect(result).toBe('warning');
        result = pipe.transform('CASH');
        expect(result).toBe('primary');
        result = pipe.transform('CREDIT');
        expect(result).toBe('info');
        result = pipe.transform('INSURANCE');
        expect(result).toBe('info');
        result = pipe.transform('EMPLOYER');
        expect(result).toBe('info');
        result = pipe.transform('PATIENT');
        expect(result).toBe('info');
        result = pipe.transform('SENT');
        expect(result).toBe('info');
        result = pipe.transform('UNDELIVERED');
        expect(result).toBe('warning');
        result = pipe.transform('DRAFT');
        expect(result).toBe('warning');
        result = pipe.transform('ASAP');
        expect(result).toBe('warning');
        result = pipe.transform('NO_SHOW');
        expect(result).toBe('warning');
        result = pipe.transform('WAITING');
        expect(result).toBe('warning');
        result = pipe.transform('PENDING');
        expect(result).toBe('warning');
        result = pipe.transform('draft');
        expect(result).toBe('warning');
        result = pipe.transform('Draft');
        expect(result).toBe('warning');
        result = pipe.transform('REQUESTED');
        expect(result).toBe('warning');
        result = pipe.transform('IN_PROGRESS');
        expect(result).toBe('info');
        result = pipe.transform('Not At Risk');
        expect(result).toBe('success');
        result = pipe.transform('At Risk');
        expect(result).toBe('danger');
        result = pipe.transform('FAILED');
        expect(result).toBe('danger');
        result = pipe.transform('High Risk');
        expect(result).toBe('danger');
        result = pipe.transform('Low Risk');
        expect(result).toBe('warning');
        result = pipe.transform('Average Risk');
        expect(result).toBe('warning');

        result = pipe.transform('Yes');
        expect(result).toBe('success');
        result = pipe.transform('No');
        expect(result).toBe('danger');
        result = pipe.transform('Linked');
        expect(result).toBe('success');
        result = pipe.transform('Unlinked');
        expect(result).toBe('danger');
        result = pipe.transform('Valid');
        expect(result).toBe('success');
        result = pipe.transform('Invalid');
        expect(result).toBe('danger');
        result = pipe.transform('EMERGENCY');
        expect(result).toBe('danger');

        result = pipe.transform('Retired');
        expect(result).toBe('danger');
        result = pipe.transform('cancelled');
        expect(result).toBe('danger');
        result = pipe.transform('RETIRED');
        expect(result).toBe('danger');

        result = pipe.transform('Mapped');
        expect(result).toBe('secondary');
        result = pipe.transform('MAPPED');
        expect(result).toBe('secondary');
        result = pipe.transform('FULFILLED');
        expect(result).toBe('secondary');
        result = pipe.transform('FINALIZED_PROVIDER');
        expect(result).toBe('primary');

        result = pipe.transform('Returned');
        expect(result).toBe('warning');
        result = pipe.transform('requested');
        expect(result).toBe('warning');
        result = pipe.transform('RETURNED');
        expect(result).toBe('warning');

        result = pipe.transform('REVIEWED');
        expect(result).toBe('info');
        result = pipe.transform('Reviewed');
        expect(result).toBe('info');
        result = pipe.transform('CONFIRMED');
        expect(result).toBe('success');
        result = pipe.transform('APPROVED');
        expect(result).toBe('success');
        result = pipe.transform('NOT_PAID');
        expect(result).toBe('danger');
        result = pipe.transform('DECLINED');
        expect(result).toBe('danger');
        result = pipe.transform('PAID');
        expect(result).toBe('success');
        result = pipe.transform('PARTIALLY-PAID');
        expect(result).toBe('warning');
        result = pipe.transform('RECONCILED');
        expect(result).toBe('success');
        result = pipe.transform('INVALIDATED');
        expect(result).toBe('danger');
        result = pipe.transform('REJECTED');
        expect(result).toBe('danger');
        result = pipe.transform(false);
        expect(result).toBe('danger');
        result = pipe.transform('OPEN_FOR_RECON');
        expect(result).toBe('info');
        result = pipe.transform('OPEN');
        expect(result).toBe('success');
        result = pipe.transform('READY_FOR_REVIEW');
        expect(result).toBe('info');
        result = pipe.transform('INQUIRY');
        expect(result).toBe('primary');
        result = pipe.transform('PENDING_PAYMENT_UPDATE');
        expect(result).toBe('warning');
        result = pipe.transform('PAYMENT_UPDATED');
        expect(result).toBe('success');
        result = pipe.transform('NOT_LOADED');
        expect(result).toBe('warning');
        result = pipe.transform('LOADED');
        expect(result).toBe('info');
        result = pipe.transform('PARTIALLY_RECONCILED');
        expect(result).toBe('info');
        result = pipe.transform('stat');
        expect(result).toBe('danger');
        result = pipe.transform('urgent');
        expect(result).toBe('warning');
        result = pipe.transform('pending');
        expect(result).toBe('warning');

        result = pipe.transform('');
        expect(result).toBe('basic');
    });
});
