import { ReconciliationStatusPipe } from './reconciliation-status.pipe';

describe('ReconciliationStatusPipe', () => {
    it('create an instance', () => {
        const pipe = new ReconciliationStatusPipe();
        expect(pipe).toBeTruthy();
    });

    it('test status color intention', () => {
        const pipe = new ReconciliationStatusPipe();
        const res = pipe.transform('RECONCILED');
        expect(res).toBe('success');
        let result = pipe.transform('PAID');
        expect(res).toBe('success');
        result = pipe.transform('NOT_PAID');
        expect(result).toBe('danger');
        result = pipe.transform('PROCESSED');
        expect(result).toBe('primary');
        result = pipe.transform('OPEN');
        expect(result).toBe('basic');
        result = pipe.transform('CANCELLED');
        expect(result).toBe('danger');
        result = pipe.transform('REJECTED');
        expect(result).toBe('danger');
        result = pipe.transform('INVALIDATED');
        expect(result).toBe('danger');
        result = pipe.transform('PARTIALLY_PAID');
        expect(result).toBe('warning');
        result = pipe.transform('OPEN_FOR_RECON');
        expect(result).toBe('primary');
        result = pipe.transform('INQUIRY');
        expect(result).toBe('primary');
        result = pipe.transform('READY_FOR_REVIEW');
        expect(result).toBe('info');
        result = pipe.transform('AGREEMENT_REACHED');
        expect(result).toBe('success');
        result = pipe.transform('FINALIZED_PROVIDER');
        expect(result).toBe('primary');
        result = pipe.transform('FINALIZED_PAYER');
        expect(result).toBe('primary');
        result = pipe.transform('PENDING_PAYMENT_UPDATE');
        expect(result).toBe('warning');
        result = pipe.transform('NOT_LOADED');
        expect(result).toBe('warning');
        result = pipe.transform('LOADED');
        expect(result).toBe('primary');
        result = pipe.transform('PARTIALLY_RECONCILED');
        expect(result).toBe('warning');
        result = pipe.transform('PAYMENT_UPDATED');
        expect(result).toBe('success');
        result = pipe.transform('DECLINED');
        expect(result).toBe('danger');
        result = pipe.transform('APPROVED');
        expect(result).toBe('success');
        result = pipe.transform('Declined');
        expect(result).toBe('danger');
        result = pipe.transform('Duplicate');
        expect(result).toBe('warning');
        result = pipe.transform('Loaded');
        expect(result).toBe('primary');
        result = pipe.transform('Paid');
        expect(result).toBe('success');
        result = pipe.transform('Paid Externally');
        expect(result).toBe('success');
        result = pipe.transform('Paid To Zero');
        expect(result).toBe('success');
        result = pipe.transform('Partially Paid');
        expect(result).toBe('warning');
        result = pipe.transform('Pending Decline');
        expect(result).toBe('warning');
        result = pipe.transform('Pre-Processed');
        expect(result).toBe('primary');
        result = pipe.transform('Processed');
        expect(result).toBe('info');
        result = pipe.transform('Processed - Suspended');
        expect(result).toBe('danger');
        result = pipe.transform('QA');
        expect(result).toBe('primary');
        result = pipe.transform('Rectification');
        expect(result).toBe('info');
        result = pipe.transform('Under Investigation');
        expect(result).toBe('warning');
        result = pipe.transform('Waiting Approval');
        expect(result).toBe('info');
        result = pipe.transform('PAYER');
        expect(result).toBe('info');
        result = pipe.transform('PROVIDER');
        expect(result).toBe('info');
        result = pipe.transform('SHARED');
        expect(result).toBe('info');
        result = pipe.transform('NOT_ASSIGNED');
        expect(result).toBe('warning');

        result = pipe.transform('');
        expect(result).toBe('basic');
    });
});
