/**
 * The file contents for the current environment will overwrite these during build.
 * The build system defaults to the dev environment which uses `environment.ts`
 */
export const environment = {
    firebase: {
        apiKey: process.env.NG_APP_FIREBASEAPIKEY,
        authDomain: process.env.NG_APP_FIREBASEAUTHDOMAIN,
        projectId: process.env.NG_APP_FIREBASEPROJECTID,
        storageBucket: process.env.NG_APP_FIREBASESTORAGEBUCKET,
        messagingSenderId: process.env.NG_APP_FIREBASEMESSAGINGSENDERID,
        appId: process.env.NG_APP_FIREBASEAPPID,
    },
    flagsmithClientSideKey: process.env.NG_APP_FLAGSMITHENVIRONMENT,
    sentryEnvironment: process.env.NG_APP_SENTRYENVIRONMENT,
    sentryDsn: process.env.NG_APP_SENTRYDSN,
    production: process.env.NG_APP_IS_PRODUCTION,
    displayFeature: process.env.NG_APP_DISPLAY_FEATURE_IN_TESTING,
    serverURL: process.env.NG_APP_SERVERURL,
    surveyURL: process.env.NG_APP_SURVEYSERVERURL,
    erpServerURL: process.env.NG_APP_ERPSERVERURL,
    crmServerUrl: process.env.NG_APP_CRMSERVERURL,
    autoreconUrl: process.env.NG_APP_AUTORECON_URL,
    mdaktariUrl: process.env.NG_APP_MDAKTARIURL,
    ediServerURL: process.env.NG_APP_EDISERVERURL,
    isServerURL: process.env.NG_APP_ISSERVERURL,
    clinicalServerURL: process.env.NG_APP_CLINICALSERVERURL,
    clinicalRestUrl: process.env.NG_APP_CLINICALRESTURL,
    commsServerURL: process.env.NG_APP_COMMSSERVERURL,
    variant: process.env.NG_APP_VARIANT,
    billingBackend: process.env.NG_APP_BILLING_BACKEND_URL,
    authWithKeyCloak: process.env.NG_APP_USE_KEYCLOAK,
    onBoardingURL: process.env.NG_APP_ONBOARDINGURL,
    AUTH_SERVER_DOMAIN: process.env.NG_APP_AUTHSERVERURL,
    CLIENT_ID: process.env.NG_APP_CLIENTID,
    ssrClientID: process.env.NG_APP_CLIENTID_SSR,
    ssrClientSecret: process.env.NG_APP_CLIENT_SECRET_SSR,
    ME: process.env.NG_APP_ME,
    ERPME: process.env.NG_APP_ERPME,
    bp_type: 'PROVIDER',
    ACTIONS: {
        RESTRICT: [],
        CHECKERS: ['ActionChecker', 'AuthorizationChecker'],
        PAGECHECKERS: ['PageActions'],
    },
    SCOPES: ['auth.me.read', 'integration.*', 'erp.*'],
    TIMEOUT: {
        idle: process.env.NG_APP_TIMEOUT_IDLE,
        warning: process.env.NG_APP_TIMEOUT_WARNING,
    },
    AVAILABLE_HOMEPAGES: ['/features/lending'],
    /** CubeJS config options */
    CUBEJS_API_URL: process.env.NG_APP_CUBEJSAPIURL,
    CUBEJS_LOGIN_URL: process.env.NG_APP_CUBEJSLOGINURL,
    CUBEJS_API_SECRET: process.env.NG_APP_CUBEAPISECRET,
    /** Superset config options */
    supersetServerUrl: process.env.NG_APP_SUPERSET_SERVER_URL,
    supersetUsername: process.env.NG_APP_SUPERSET_USERNAME,
    supersetPassword: process.env.NG_APP_SUPERSET_PASSWORD,
    appointmentsDashboardUuid: process.env.NG_APP_APPOINTMENTS_DASHBOARD_UUID,
    billingDashboardUuid: process.env.NG_APP_BILLING_DASHBOARD_UUID,
    financeDashboardUuid: process.env.NG_APP_FINANCE_DASHBOARD_UUID,
    etimsDashboardUuid: process.env.NG_APP_ETIMS_DASHBOARD_UUID,
    inventoryDashboardUuid: process.env.NG_APP_INVENTORY_DASHBOARD_UUID,
    patientsDashboardUuid: process.env.NG_APP_PATIENTS_DASHBOARD_UUID,
    visitsDashboardUuid: process.env.NG_APP_VISITS_DASHBOARD_UUID,
    healthCrmDashboardUuid: process.env.NG_APP_HEALTH_CRM_DASHBOARD_UUID,
    messagesDashboardUuid: process.env.NG_APP_MESSAGES_DASHBOARD_UUID,
    googleMapsApiKey: process.env.NG_APP_GOOGLE_MAPS_API_KEY,
    messageGoogleMapKey: process.env.NG_APP_MESSAGE_GOOGLE_MAP_KEY,
    jsdKey: process.env.NG_APP_JSD_KEY,
    /** Keycloak config options */
    keycloak: {
        authURL: process.env.NG_APP_KEYCLOAK_AUTH_URL,
        realm: process.env.NG_APP_KEYCLOAK_REALM,
        clientId: process.env.NG_APP_KEYCLOAK_CLIENT_ID,
        pkceMethod: process.env.NG_APP_KEYCLOAK_PKCE_METHOD,
        redirectUri: process.env.NG_APP_KEYCLOAK_REDIRECT_URI,
        logoutRedirectUri: process.env.NG_APP_KEYCLOAK_POST_LOGOUT_REDIRECT_URI,
    },
};
